// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTrazor_agent returns the embedded CollectionSpec for trazor_agent.
func loadTrazor_agent() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Trazor_agentBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trazor_agent: %w", err)
	}

	return spec, err
}

// loadTrazor_agentObjects loads trazor_agent and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trazor_agentObjects
//	*trazor_agentPrograms
//	*trazor_agentMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrazor_agentObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrazor_agent()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trazor_agentSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trazor_agentSpecs struct {
	trazor_agentProgramSpecs
	trazor_agentMapSpecs
	trazor_agentVariableSpecs
}

// trazor_agentProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trazor_agentProgramSpecs struct {
	GetConnStart    *ebpf.ProgramSpec `ebpf:"get_conn_start"`
	GetLatencyOnEnd *ebpf.ProgramSpec `ebpf:"get_latency_on_end"`
}

// trazor_agentMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trazor_agentMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	Latency *ebpf.MapSpec `ebpf:"latency"`
}

// trazor_agentVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trazor_agentVariableSpecs struct {
}

// trazor_agentObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrazor_agentObjects or ebpf.CollectionSpec.LoadAndAssign.
type trazor_agentObjects struct {
	trazor_agentPrograms
	trazor_agentMaps
	trazor_agentVariables
}

func (o *trazor_agentObjects) Close() error {
	return _Trazor_agentClose(
		&o.trazor_agentPrograms,
		&o.trazor_agentMaps,
	)
}

// trazor_agentMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrazor_agentObjects or ebpf.CollectionSpec.LoadAndAssign.
type trazor_agentMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	Latency *ebpf.Map `ebpf:"latency"`
}

func (m *trazor_agentMaps) Close() error {
	return _Trazor_agentClose(
		m.Events,
		m.Latency,
	)
}

// trazor_agentVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrazor_agentObjects or ebpf.CollectionSpec.LoadAndAssign.
type trazor_agentVariables struct {
}

// trazor_agentPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrazor_agentObjects or ebpf.CollectionSpec.LoadAndAssign.
type trazor_agentPrograms struct {
	GetConnStart    *ebpf.Program `ebpf:"get_conn_start"`
	GetLatencyOnEnd *ebpf.Program `ebpf:"get_latency_on_end"`
}

func (p *trazor_agentPrograms) Close() error {
	return _Trazor_agentClose(
		p.GetConnStart,
		p.GetLatencyOnEnd,
	)
}

func _Trazor_agentClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trazor_agent_bpfel.o
var _Trazor_agentBytes []byte
